### ISSUE TITLE
Can not invoke method ...findResource(String,boolean) with the passed arguments; they do not match

### ISSUE THREAD

**Issue by Download** [nodyn/jvm-npm#17]
I am trying to load my little library [picolog](download.github.io/picolog) in Nashorn using this awesome library (thank you btw!) but unfortunately it's not working. I get:

> javax.script.ScriptException: TypeError: Can not invoke method [jdk.internal.dynalink.beans.SimpleDynamicMethod URL org.jboss.modules.ModuleClassLoader.findResource(String,boolean)] with the passed arguments; they do not match any of its method signatures. in vfs:/.../jvm-npm.js at line number 240

I peeked at [line 240](https://github.com/nodyn/jvm-npm/blob/e2935212b89e32dd0dce042a5c8e1268bab58e56/src/main/javascript/jvm-npm.js#L240) and it's indeed a call to `findResource` but with only one argument... 

I'm very new to Nashorn so I have no idea what to do now... Could this be an error in my script?

(btw, I know my library won't run (yet) in Nashorn, but I want to try to run it so I can fix it)

**Comment by Download** [comment]
This small change seems to fix it. However now I get 'module not found' even though picolog is in the NPM registry.

I am using this library standalone but I'm starting to wonder whether I am doing it all wrong. Anyways, I'll stop ranting now  :)  Looking forward to your response.

**Comment by lance** [comment]
@Download can you provide a reproducible, failing test case for your module not found issue? If so, I will take a look. This hasn't been formally (or even informally as far as I know) tested against WildFly. I have suspicions this may be the culprit. Nashorn should definitely be supported. Glad you are finding this useful.

**Comment by Download** [comment]
Ok I will try... if you promise to re-open when I do  :)

**Comment by Download** [comment]
Question: Where does jvm-npm expect the node_modules folder?
I just realized in my total n00biness I probably completely messed that part up...

**Comment by lance** [comment]
@Download node_modules is typically in the project directory, but jvm-npm should search all of the locations that standard npm does.

**Comment by Download** [comment]
But what does 'the project directory' mean in the context of Nashorn? The 'current working directory'?
