### ISSUE TITLE
Incorrect usage of Function constructor, as such doesn't work on all environments

### ISSUE THREAD

**Issue by p-bakker** [nodyn/jvm-npm#37]
Module._load uses a function constructor like this:

```javascript
var args = ['exports', 'module', 'require', '__filename', '__dirname'];
var func = new Function(args, body);
```

While this seems to work on some environments, it is not according to the specs and doesn't work on all environments (for example (older versions of?) Rhino). 

Instead the argument names need to be supplied as individual arguments to the constructor like:

```javascript
var func = new Function('exports', 'module', 'require', '__filename', '__dirname', body);
```

See http://www.ecma-international.org/ecma-262/5.1/#sec-15.3 for the specs

**Comment by lance** [comment]
Good catch; interesting that I haven't seen this fail before. Can you point to specific interpreters where the existing implementation fails?

**Comment by p-bakker** [comment]
Am (unfortunately) stuck on using a quite old Rhino version (1.7R2), haven't tested on the latest

Something else I noticed: several callsites of normalizeName pass in '.js' as default for the ext param, while normalizeName also has code to use that as default. A bit of redundant code
